export { SignUpPage } from 'pages/Auth';
export { SignUpPage2 } from 'pages/Auth';
export { SignInPage } from 'pages/Auth';
export { PasswordResetOne } from 'pages/Auth';
export { PasswordResetTwo } from 'pages/Auth';
export { PasswordResetThree } from 'pages/Auth';
export { ResetPasswordPage } from 'pages/Auth';
export { PasswordResetFive } from 'pages/Auth';
export { OverviewPage } from 'pages/dashboard';
